// range_boundary.js — Generated by NEXUS Strategy Builder
// Fade moves to BB extremes. Buy near lower band with RSI oversold, sell near upper.

export const RangeBoundaryStrategy = {

    checkEntry(candles, rsiState, h4Candles) {
        if (candles.length < 20) return null;

        const closed = candles.slice(0, -1);
        const bar    = closed[closed.length - 1];
        const prev   = closed[closed.length - 2];
        if (!bar || !prev) return null;

        // ── INDICATORS ──
        const rsi     = _calcRSI(closed, rsiState);
        const ema8    = _ema(closed, 8);
        const ema20   = _ema(closed, 20);
        const ema50   = _ema(closed, 50);
        const ema200  = _ema(closed, 200);
        const atr     = _atr(closed, 14);
        const bb      = _bb(closed, 20, 2);
        const h4ema21 = h4Candles?.length >= 21 ? _ema(h4Candles, 21) : null;
        const vwap    = _vwap(closed);
        const prevHigh = Math.max(...closed.slice(-20).map(c => c.high));
        const prevLow  = Math.min(...closed.slice(-20).map(c => c.low));
        const candleBody = Math.abs(bar.close - bar.open) / (atr || 1);



        // ── SELL SIGNAL ──
        const sellSignal =
            bar.close < bb?.upper &&
            rsi != null && rsi > 65;
        if (sellSignal) {
            return { type: 'SELL', label: 'Range Boundary Sell',
                     slMultiplier: 1.5, tpMultiplier: 2 };
        }

        return null;
    },
};

// ── INDICATOR HELPERS ──
function _ema(candles, period) {
    if (candles.length < period) return null;
    const k = 2 / (period + 1);
    let e = candles.slice(0, period).reduce((s, c) => s + c.close, 0) / period;
    for (let i = period; i < candles.length; i++) e = candles[i].close * k + e * (1 - k);
    return e;
}
function _calcRSI(candles, state, period = 14) {
    if (candles.length < 2) return 50;
    const d = candles[candles.length-1].close - candles[candles.length-2].close;
    const g = d > 0 ? d : 0, l = d < 0 ? -d : 0;
    if (!state.initialized) { state.prevAvgGain = g; state.prevAvgLoss = l; state.initialized = true; }
    const k = 1/period;
    state.prevAvgGain = state.prevAvgGain*(1-k) + g*k;
    state.prevAvgLoss = state.prevAvgLoss*(1-k) + l*k;
    return state.prevAvgLoss === 0 ? 100 : 100 - 100/(1 + state.prevAvgGain/state.prevAvgLoss);
}
function _atr(candles, period = 14) {
    if (candles.length < period+1) return null;
    const trs = candles.slice(1).map((c,i)=>Math.max(c.high-c.low,Math.abs(c.high-candles[i].close),Math.abs(c.low-candles[i].close)));
    return trs.slice(-period).reduce((a,b)=>a+b,0)/period;
}
function _bb(candles, period = 20, mult = 2) {
    if (candles.length < period) return null;
    const slice = candles.slice(-period).map(c => c.close);
    const mid   = slice.reduce((a,b)=>a+b,0)/period;
    const std   = Math.sqrt(slice.reduce((s,v)=>s+(v-mid)**2,0)/period);
    return { upper: mid+mult*std, lower: mid-mult*std, mid };
}
function _vwap(candles) {
    let tv = 0, tpv = 0;
    candles.forEach(c => { const v = c.volume || 1; tv += v; tpv += ((c.high+c.low+c.close)/3)*v; });
    return tv > 0 ? tpv/tv : candles[candles.length-1]?.close;
}